sudo: required #tell travis we need super user privileges
service:
  - docker

before_install:
  - docker build -t kaery1000/docker-react -f Dockerfile.dev .

script:
  - docker run kaery1000/docker-react npm run test -- --coverage
  
